## ANS-1:
SELECT ID FROM SKILLS 
GROUP BY ID
HAVING COUNT(SKILLS) = (
SELECT COUNT(DISTINCT(SKILLS)) FROM SKILLS);

## ANS-2;
SELECT PRODUCT_ID FROM PRODUCT_INFO
WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM PRODUCT_INFO_LIKES);